version: 1.2
tools:
   - subclass: cwl
     primaryDescriptorPath: /Dockstore.cwl
     publish: false
     testParameterFiles:
         - /test.json
     authors:
         - orcid: 0000-0001-7641-7724
         - name: SEAB-5999
